openapi: 3.0.2
servers:
  - url: /wpgTransit/api/
info:
  description: |-
    This is a Winnipeg Transit Server based on the OpenAPI 3.0 
      specification.
  version: 1.0.0
  title: Winnipeg Transit API - OpenAPI 3.0
tags:
  - name: bus
    description: Everything about Winnipeg Transit buses
  - name: fare
    description: Access to different transit fares
paths:
  '/ticketFare/{age}':
    get:
      tags:
        - fare
      summary: Find fare type by age
      description: Returns a list of fares for an age group
      operationId: getTicketFareByAge
      parameters:
        - name: age
          in: path
          description: age that determines passenger fare type to return
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Fare'
        '400':
          description: Invalid age supplied
        '404':
          description: fare type not found
  /peggoPass/:
    get:
      tags:
        - fare
      summary: Access peggo pass types
      description: Returns the list of peggo pass types
      operationId: getAllPeggoPassTypes
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Peggo'
        '404':
          description: Not Found
  /getAllBusRoutes/:
    get:
      tags:
        - bus
      summary: Access all bus routes 
      description: Returns the list of all bus routes
      operationId: getAllBusRoutes
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Bus'
        '404':
          description: Not Found
components:
  schemas:
    Fare:
      properties:
        id:
          type: integer
          format: int32
          example: 01
        type:
          type: string
          example: Senior Fare
        cash_price:
          type: number
          example: 2.5
        ticket_price:
          type: number
          example: 1.33
        monthly_pass_price:
          type: number
          example: 51.05
    Peggo: 
      properties: 
        id: 
          type: integer
          format: int64
          example: 01
        fare_type: 
          type: string
          example: "Reduced fare"
        colour:
          type: string
          example: "Green"
        status:
          type: string
          description: pet status in the store
          enum:
            - available
            - pending
            - sold
    Bus:
      properties: 
        id: 
          type: integer
          format: int64
          example: 1
        bus_number:
          type: integer
          format: int64
          example: 74
        route_name:
          type: string
          example: "Kenaston"
        start_location: 
          type: string
          example: "Polo Park"
        end_location: 
          type: string
          example: "Universoty of Manitoba"
    
        


  
